### ISSUE TITLE
Disk file

### ISSUE THREAD

**Issue by NHSE** [aclich/PYNQ-Z2_Mask_Detection_Sreaming_system#1]
The disk file is corrupted
Please solve it

**Comment by aclich** [comment]
Hi, Please try the updated image file.
https://drive.google.com/file/d/1seN3JbUqXAViNvDaH-hraOcrsKgmP8KR/view?usp=sharing

**Comment by NHSE** [comment]
How do I configure SSH communication?

**Comment by NHSE** [comment]
SSH connection not working
Could you please help me?

**Comment by aclich** [comment]
Hi, please visit the jupyter-notebook on pynq-z2 and use terminal from it.
Try following command.
```
sudo sed -i 's@192.168.2.165@0.0.0.0@g' /etc/ssh/sshd_config && sudo systemctl restart ssh
```

There are some configure shouldn't be in image. I'll fix the image if I'm available.

**Comment by aclich** [comment]
If you connect the board with router and hope to get address through DHCP, please modify **_/etc/network/interfaces.d/eth0_** as following
```
auto eth0
iface eth0 inet dhcp

auto eth0
iface eth0 inet static
address 192.168.2.99
netmask 255.255.255.0
```

**Comment by NHSE** [comment]
![image](https://user-images.githubusercontent.com/97014948/168069398-4a447b37-ab0c-4141-84ea-4d5f26fb83a3.png)
I successfully proceeded with SSH connection. However, YOLO does not proceed as shown in the picture above.

**Comment by NHSE** [comment]
![image](https://user-images.githubusercontent.com/97014948/168071449-ffcf1392-7c1d-4585-adf8-876de5162185.png)
The command Make is not executed either.

**Comment by aclich** [comment]
Have you tried with root user?

**Comment by NHSE** [comment]
Yes, but it doesn't change to root user

**Comment by aclich** [comment]
I just flash the SD card and build this repo again. It seems no problem. Make sure you follow the steps in quick start.

![image](https://user-images.githubusercontent.com/71011237/168086062-cf49994a-910e-4fbd-b9f8-b0578399c4f2.png)

**Comment by NHSE** [comment]
How did you enter the root user? Plz give me your code in ssh program

**Comment by aclich** [comment]
1. sudo su
2. Login ssh with root
Password is “xilinx”

**Comment by NHSE** [comment]
My board login ID doesn't work as root user

**Comment by aclich** [comment]
The image has already configured with root login permission. Have you change any ssh config on the board?

**Comment by NHSE** [comment]
When i login this ssh progarm as root user, it displayed "login incorrect"

**Comment by aclich** [comment]
Make sure your **_/etc/ssh/sshd_config_** file with following setting
```

PermitRootLogin yes

```
And reboot once if you make changes.

**Comment by NHSE** [comment]
![image](https://user-images.githubusercontent.com/97014948/168132173-62167a2d-23f5-4c72-9f57-e20f6d154a08.png)
I proceeded as a root user, but if I proceed with the code "./yolo YouTube_320.mp4v", the SSH connection will be disconnected.
I have proceeded with the whole process as you said

**Comment by NHSE** [comment]
![image](https://user-images.githubusercontent.com/97014948/168132934-e82f1fee-b94d-4629-96f0-8b8c908981f1.png)
This code is also the same

**Comment by aclich** [comment]
Are you power the board by usb? If so, probably not enough power from usb. Please use DC 9v to power the board.

**Comment by NHSE** [comment]
Thanks to you, it's settled. Thank you.
But I have another question. Can you send the 'box size' to Jupiter's laptop right away and make Arduino pin behave differently depending on the 'box size'?

**Comment by aclich** [comment]
I close this issue since the problem seems solved.
For other applications, feel free to modiy the code in **_src/_**.
I'm sure there are some serial port libs that can help you communicate with Arduino.

**Comment by NHSE** [comment]
Can you show me the vivado ip design?

**Comment by aclich** [comment]
@NHSE Sorry for the late response. Please refer to this [xsa file](https://drive.google.com/file/d/1296fhViqp1naxSPvR30yYj0aSpSZ1kFk/view?usp=sharing).
I think you are able to rebuild the hardware design from the tcl in it.
